name = "ObaraSaika"
uuid = "b41fb182-4529-41f5-8c95-569560f9f6de"
authors = ["Michael F. Herbst <info@michael-herbst.com> and contributors"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
SpecialFunctions = "0.10"
julia = "1.5"

[extras]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "PyCall", "QuadGK"]
